server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://192.168.170.100:3306/phase1_dev?serverTimezone=GMT%2b8
    username: root
    password: 'symbio@2018'
    testWhileIdle:  true
    timeBetweenEvictionRunsMillis:  3600000
    validationQuery:  SELECT 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    open-in-view: true


  file:
      root: ${home}/dashboard
