
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2b8
    username: root
    password: Root123456
    testWhileIdle:  true
    timeBetweenEvictionRunsMillis:  3600000
    validationQuery:  SELECT 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    open-in-view: true


  file:
      root: ${home}/dashboard
