server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://192.168.170.100:3306/phase1_dev?serverTimezone=GMT%2b8
    username: root
    password: 'symbio@2018'
    testWhileIdle:  true
    timeBetweenEvictionRunsMillis:  3600000
    validationQuery:  SELECT 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    open-in-view: true

  file:
    root: ${home}/dashboard

logging:
  level:
    root: info #trace, debug, info, warn, error
  pattern:
    console: "%d - %msg%n" #     定义打印的日志格式
    #    dateformat: #设置日志日期格式
    #    file: #定义输出到日志文件的日志格式
    #  config: #日志配置文件的位置。例如，classpath:logback.xml。
    file: dashboard.log #设置保存日志的日志文件
    #    max-history:
    #    max-size: #设置日志文件最大大小 #设置日志等级
    #path: / #日志文件的位置，例如/var/log
    register-shutdown-hook: false #当初始化日志系统时，为其注册一个关闭钩子。
